name: Deploy to Firebase Hosting
on:
    push:
        branches:
            - main
            - dev
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Expo
              uses: expo/expo-github-action@v7
              with:
                  expo-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: run expo publish
              run: expo publish --non-interactive